config/routes.rb
Rails.application.routes.draw do
  get    '/tasks/new',     to: 'tasks#new'
  post   '/tasks',         to: 'tasks#create'

  get    '/tasks',         to: 'tasks#index'
  get    '/tasks/:id',     to: 'tasks#show', as: 'task'

  get    'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id',      to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field  :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area  :details, class: 'form-control' %>
  </div>

  <div class="form-check my-4">
      <%= f.check_box :completed, class: "form-check-input" %>
      <label class="form-check-label" for="defaultCheck1">
        completed
      </label>
  </div>

  <%= f.submit class: 'btn btn-primary'%>
  <div class="dropdown-divider my-4"></div>
  <i class="fa fa-history icons" aria-hidden="true"></i>
  <%= link_to 'Back to list', tasks_path %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<div class="form-check mt-4">
  <% @tasks.each do |task| %>
    <div class="row col-12">
      <input class="form-check-input" type="checkbox" value="">
      <label class="form-check-label" for="defaultCheck1">
        <%= link_to task.title, task_path(task) %>
      </label>
      <div>
        ・<%= link_to task_path(task), method: :delete, data: { confirm: "Delete #{task.title}?"} do %>
          <i class="fa fa-trash icons" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="dropdown-divider my-4"></div>
<i class="fa fa-plus icons" aria-hidden="true"></i>
<%= link_to 'Add new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="d-flex justify-content-between">

  <div>
    <h1>
      <%= @task.title %>
    </h1>
  </div>

  <div>
    <%= link_to edit_path, class: 'btn border' do%>
      <i class="fa fa-pencil icons" id="edit-task-button" aria-hidden="true"></i>
      Edit this task
    <% end %>
  </div>

</div>

<div class="alert alert-secondary p-4" role="alert">
  <%= @task.details %>
</div>

<div class="form-check mt-4">
    <input class="form-check-input" type="checkbox" <%= @task.completed ? 'checked' : '' %>>
    <label class="form-check-label" for="defaultCheck1">
      <% if @task.completed %>
        This task is completed
      <% else %>
        This task is not completed yet
      <% end %>
    </label>
</div>

<div class="dropdown-divider my-4"></div>

<i class="fa fa-history icons" aria-hidden="true"></i>
<%= link_to 'Back to list', tasks_path %>